# -*- coding: utf-8 -*-
{
    'name': 'Connecta VAS',
        'version': '19.0.1.95.0',
    'post_init_hook': 'post_init_hook',
    'category': 'Accounting',
    'author': 'Connecta Solutions',
    'website': 'https://connecta.vn',
    'license': 'OEEL-1',
    'depends': [
        'base',
        'base_setup',
        'account',
        # account_asset: TÍCH HỢP MỀM (source_mode=odoo_asset). Không hard-depend —
        # tránh kéo accountant chain / khơi lỗi EE industry_fsm+billing_type.
        # account_loans: BỎ QUA (W7 tự tính lãi) — không hard-depend.
        # hr_payroll: TÍCH HỢP MỀM (W9 payroll adapter). Không hard-depend.
        # point_of_sale: TÍCH HỢP MỀM (POS adapter). Không hard-depend.
        # mrp: TÍCH HỢP MỀM (gợi ý BOM Chặng 6). Không hard-depend.
        'stock',
        'stock_account',
        'stock_landed_costs',
        'sale_stock',
        'purchase_stock',
        'hr',
        'hr_expense',
        'web',
    ],
    'data': [
        'security/vas_import_vat_security.xml',
        'security/vas_costing_security.xml',
        'security/ir.model.access.csv',
        'data/vas_regime_data.xml',
        'data/vas_journals.xml',
        'data/vas_account_tt133.xml',
        'data/vas_tax_seed.xml',
        'data/vas_tax_deduction_rule_seed.xml',
        'data/vas_gtgt_declaration_seed.xml',
        'data/vas_gtgt_reduction_exclusion_seed.xml',
        'data/vas_gtgt_direct_seed.xml',
        'data/vas_closing_rule_tt133.xml',
        'data/vas_report_line_b01a_tt133.xml',
        'data/vas_report_line_b02_tt133.xml',
        'data/vas_report_line_b03_tt133.xml',
        'data/vas_report_line_b09_tt133.xml',
        'data/vas_account_map_tt133.xml',
        'data/vas_asset_group_tt45.xml',
        'data/vas_rule_tt133_w1.xml',
        'data/vas_rule_tt133_w2.xml',
        'data/vas_rule_tt133_w3.xml',
        'data/vas_rule_tt133_w4.xml',
        'data/vas_rule_tt133_w5.xml',
        'data/vas_rule_tt133_w6.xml',
        'data/vas_rule_tt133_w7.xml',
        'data/vas_rule_tt133_w8.xml',
        'data/vas_rule_tt133_w9.xml',
        'data/vas_rule_tt133_payroll.xml',
        'data/vas_rule_tt133_pos.xml',
        'data/vas_sync_cron.xml',
        'data/vas_w10_click_demo.xml',
        'data/vas_w11_bctc_demo.xml',
        'data/vas_cost_item_seed.xml',
        'data/vas_cost_object_matrix.xml',
        'data/vas_variance_data.xml',
        'data/vas_ops_data.xml',
        'views/vas_catalog_views.xml',
        'views/vas_dashboard_views.xml',
        'views/vas_ops_views.xml',
        'views/vas_costing_views.xml',
        'views/vas_allocation_views.xml',
        'views/vas_costing_stage3_views.xml',
        'views/vas_costing_warehouse_views.xml',
        'views/vas_variance_views.xml',
        'views/vas_closing_rule_views.xml',
        'views/vas_closing_entry_views.xml',
        'views/vas_account_map_views.xml',
        'views/vas_landed_tax_map_views.xml',
        'views/vas_move_views.xml',
        'views/vas_rule_views.xml',
        'views/vas_debt_offset_views.xml',
        'views/vas_inventory_provision_views.xml',
        'views/vas_debt_aging_views.xml',
        'views/vas_import_vat_views.xml',
        'views/vas_tax_deduction_views.xml',
        'views/vas_gtgt_declaration_views.xml',
        'views/vas_gtgt_listing_views.xml',
        'views/vas_gtgt_reduction_views.xml',
        'views/vas_gtgt_supplement_views.xml',
        'views/vas_gtgt_direct_views.xml',
        'views/vas_opening_balance_views.xml',
        'views/vas_asset_views.xml',
        'views/vas_loan_views.xml',
        'views/vas_capital_in_kind_views.xml',
        'views/vas_payroll_department_map_views.xml',
        'views/vas_account_ledger_views.xml',
        'report/vas_account_ledger_report.xml',
        'views/vas_trial_balance_views.xml',
        'report/vas_trial_balance_report.xml',
        'report/vas_fs_report.xml',
        'views/vas_b01a_views.xml',
        'views/vas_b02_views.xml',
        'views/vas_b03_views.xml',
        'views/vas_b09_views.xml',
        'views/vas_b09_entry_views.xml',
        'views/account_payment_views.xml',
        'views/account_move_views.xml',
        'views/hr_expense_views.xml',
        'views/res_config_settings_views.xml',
    ],
        'assets': {
        'web.assets_backend': [
            'connecta_vas/static/src/vas_report/**/*',
            'connecta_vas/static/src/vas_ops/**/*',
            'connecta_vas/static/src/vas_dashboard/**/*',
            'connecta_vas/static/src/vas_costing_m5/**/*',
            'connecta_vas/static/src/vas_debt_aging/**/*',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
