# -*- coding: utf-8 -*-
# res_company phải nạp trước vas_account_map_review: Odoo chạy _auto_init/init lần
# lượt theo thứ tự model, mà view SQL của màn rà soát đọc res_company.vas_regime_id.
from . import res_company
from . import vas_regime
from . import vas_account
from . import vas_closing_rule
from . import vas_closing_entry
from . import vas_journal
from . import vas_fiscalyear
from . import vas_period
from . import vas_tax
from . import vas_tax_deduction_rule
from . import vas_full_reconcile
from . import vas_move
from . import vas_move_line
from . import vas_tax_deduction_check
from . import vas_input_tax_purpose_wizard
from . import vas_gtgt_catalog
from . import vas_gtgt_declaration
from . import vas_gtgt_listing
from . import vas_gtgt_reduction
from . import vas_gtgt_supplement
from . import vas_gtgt_direct
from . import product_template
from . import vas_rule
from . import vas_rule_line
from . import vas_account_map
from . import vas_account_map_review
from . import vas_landed_tax_map
from . import vas_asset_group
from . import vas_asset
from . import vas_loan
from . import vas_profit_distribution
from . import vas_capital_in_kind
from . import vas_payroll_department_map
from . import vas_sync
from . import vas_sync_pos
from . import vas_sync_inventory
from . import vas_inventory_provision
from . import vas_cash_flow_activity
from . import vas_debt_offset
from . import vas_import_vat
from . import account_payment
from . import account_move_line
from . import hr_expense
from . import vas_opening_balance
from . import vas_books_mixin
from . import vas_books_aggregate
from . import vas_report_engine
from . import vas_report_print
from . import vas_report_dummy
from . import vas_account_ledger
from . import vas_trial_balance
from . import vas_report_line
from . import vas_report_snapshot
from . import vas_b01a
from . import vas_b02
from . import vas_b03
from . import vas_b09
from . import vas_b09_meta  # noqa: F401 — dữ liệu phân loại B09
from . import vas_b09_entry
from . import res_config_settings
from . import vas_cost_item
from . import vas_cost_object
from . import vas_costing_period
from . import vas_allocation_config
from . import vas_allocation_run
from . import vas_costing_flow
from . import vas_costing_wizard
from . import vas_costing_warehouse
from . import vas_costing_immediate
from . import vas_variance
from . import vas_variance_sheet
from . import vas_variance_line
from . import vas_variance_bom
from . import vas_ops
from . import vas_dashboard
from . import vas_debt_aging
from . import vas_costing_m5
